### ISSUE TITLE
list size smaller then size

### ISSUE THREAD

**Issue by niekosau** [niekosau/s3ben#21]
Traceback (most recent call last):
  File "/var/lib/s3ben/.local/bin/s3ben", line 8, in <module>
    sys.exit(main())
  File "/var/lib/s3ben/.local/lib/python3.9/site-packages/s3ben/cli.py", line 35, in main
    parsed_args.func(config, parsed_args)
  File "/var/lib/s3ben/.local/lib/python3.9/site-packages/s3ben/cli.py", line 166, in sync
    backup.sync_bucket_files(args.bucket, args.threads)
  File "/var/lib/s3ben/.local/lib/python3.9/site-packages/s3ben/backup.py", line 78, in sync_bucket_files
    splited_objects = list_split(all_objects, elements)
  File "/var/lib/s3ben/.local/lib/python3.9/site-packages/s3ben/helpers.py", line 25, in list_split
    return [input[i:i + size] for i in range(0, len(input), size)]
ValueError: range() arg 3 must not be zero

**Comment by niekosau** [comment]
not relevent anymore
